edition = "2018"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
reorder_imports = true
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_args_layout = "Vertical"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1